name: stats

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint --if-present
    - run: 'npm run get:repos:list'
    - name: sleep for 10s
      if: always()
      uses: juliangruber/sleep-action@v1
      with:
       time: 20s
    - name: 'get:redacted:list'
      run: 'npm run get:redacted:list'
    - name: sleep for 10s
      if: always()
      uses: juliangruber/sleep-action@v1
      with:
       time: 20s
    - name: 'add:clone:stats'
      run: 'npm run add:clone:stats --token ${{ secrets.GITHUB_TOKEN }}'
    - name: sleep for 10s
      if: always()
      uses: juliangruber/sleep-action@v1
      with:
       time: 20s
    - name: 'add:referrers:stats'
      run: 'npm run add:referrers:stats --token ${{ secrets.GITHUB_TOKEN }}'
    - name: sleep for 10s
      if: always()
      uses: juliangruber/sleep-action@v1
      with:
       time: 20s
    - name: 'add:views:stats'
      run: 'npm run add:views:stats --token ${{ secrets.GITHUB_TOKEN }}'
    - name: sleep for 10s
      if: always()
      uses: juliangruber/sleep-action@v1
      with:
        time: 20s
    - name: git set user.email
      if: always()
      run: git config --global user.email "xgirma@gmail.com"
    - name: git set user.name
      if: always()
      run: git config --global user.email "Girma Nigusse"
    - name: git set rebase false
      if: always()
      run: git config pull.rebase false
    - name: git pull
      if: always()
      run: git pull
    - name: git status
      if: always()
      run: git status
    - name: git add
      if: always()
      run: git add --all
    - name: git commit
      if: always()
      run: git commit -am "generate data for 27502"
    - name: commit data
      if: always()
      run: git push
